version: '3.9'

services:

  flowdemo:
    image: gramine-dummy-attester
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DEBUG: "${DEBUG-0}"
    environment:
      TLS: 0
      SGX: 0 #-1 for plain, 0 for gramine-direct
      DEBUG: "${DEBUG-0}"
      GRAMINE_IMG_TAG: $GRAMINE_IMG_TAG
    volumes:
      - untrustedhost:/untrustedhost
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision

volumes:
  untrustedhost:
