version: '3.9'

services:

  dummyattester:
    container_name: dummyattester
    image: gramine-dummy-attester
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DEBUG: "${DEBUG-0}"
    environment:
      DEBUG: "${DEBUG-0}"
      SGX: 1 #-1 for plain, 0 for gramine-direct
      TLS: 0
    volumes:
      - data:/data
      - untrustedhost:/untrustedhost

  dummyattester-dcap:
    container_name: dummyattester-dcap
    image: gramine-dummy-attester-dcap
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DEBUG: "${DEBUG-0}"
        RA_TYPE: "dcap"
    environment:
      DEBUG: "${DEBUG-0}"
      RA_TYPE: dcap
      SGX: 1 #-1 for plain, 0 for gramine-direct
      TLS: 0
    volumes:
      - data:/data
      - untrustedhost:/untrustedhost

volumes:
  untrustedhost:
  data:
