version: '3.9'

services:

  dummyattester:
    image: gramine-dummy-attester
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DEBUG: "${DEBUG-0}"
    environment:
      TLS: 0
      SGX: 1 #-1 for plain, 0 for gramine-direct
      DEBUG: "${DEBUG-0}"
      GRAMINE_IMG_TAG: $GRAMINE_IMG_TAG
    volumes:
      - data:/data
      - untrustedhost:/untrustedhost

  dummyattester-dcap:
    image: gramine-dummy-attester
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DEBUG: "${DEBUG-0}"
        RA_TYPE: "dcap"
    environment:
      TLS: 0
      RA_TYPE: dcap
      SGX: 1 #-1 for plain, 0 for gramine-direct
      DEBUG: "${DEBUG-0}"
      GRAMINE_IMG_TAG: $GRAMINE_IMG_TAG
    volumes:
      - data:/data
      - untrustedhost:/untrustedhost

volumes:
  untrustedhost:
  data:
